name: build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: git p7zip
    - name: Run script
      run: ./build.sh
    - name: Release
      if: env.version
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.version }}
        files: 7zip-${{ env.version }}-*.7z
        fail_on_unmatched_files: true
    - name: Setup tmate ssh session
      if: failure()
      uses: mxschmitt/action-tmate@v3
